### ISSUE TITLE
Emergency Notifications not received for certain eventIDs

### ISSUE THREAD

**Issue by ZeshanA** [real-time-footfall-analysis/rtfa-web#24]
The Simulation Test Event (`eventID = 19`), does not receive emergency notifications when one is triggered via Pusher Channels.

**Comment by RohanPadmanabhan** [comment]
I don't think this is just for event 19. Leeds (event 1) displays 0 emergencies like this:
![image](https://user-images.githubusercontent.com/26333869/49327393-00da4880-f559-11e8-89fb-c08b7f3fe68a.png)

whereas every other event (which don't seem to be getting any notifications) displays it like this:

![image](https://user-images.githubusercontent.com/26333869/49327389-f324c300-f558-11e8-97ad-e370505dc275.png)

**Comment by ZeshanA** [comment]
Resolved in #34. Cheers for the additional detail @RohanPadmanabhan, helped a lot with the debugging.
