### ISSUE TITLE
Incorrect time/date displayed on Emergency Notifications

### ISSUE THREAD

**Issue by ZeshanA** [real-time-footfall-analysis/rtfa-web#25]
This is an issue with the data stored in DynamoDB for `eventID = 1`. 

17/57 emergency notifications in the database use **milliseconds** and display the correct time on the front end. The remainder are using seconds and display an incorrect date from 1970 in the web app.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1909536/49326552-ad153280-f54b-11e8-8c13-70cd9645a3b2.png">

**Comment by ZeshanA** [comment]
@RohanPadmanabhan I suggest we wipe the Emergency Notifications database at some point and populate it with a small number (~5 total: 3 resolved, 2 unresolved) of emergencies for the demo. 

The `occurredAt` fields should have timestamp values in milliseconds **or** seconds, as long as we're consistent – which unit is the backend using now?

**Comment by RohanPadmanabhan** [comment]
I agree. Everything needs to be in seconds

**Comment by ZeshanA** [comment]
Okay, the front end time formatting functions will need to be updated to support that. Will get to it soon.

**Comment by ZeshanA** [comment]
Backend seems to now be consistent in using seconds for everything, so I've updated the front-end to reflect this. Resolved in #36.
