### ISSUE TITLE
Emergency events marked as dealt with are not updated for other users until refresh

### ISSUE THREAD

**Issue by RohanPadmanabhan** [real-time-footfall-analysis/rtfa-web#29]
When an organiser A clicks the resolve button on an emergency event it sends a notification that the event has been resolved to the server that propagates it to all open web pages through pusher (with `dealtWith` set to true). However these emergencies then don't get ticked off on organiser B's page. Organiser B has to refresh in order to see that A has dealt with the emergency

**Comment by ZeshanA** [comment]
This isn't going to be worked on before the presentation.
