### ISSUE TITLE
New organiser notifications do not appear until refresh

### ISSUE THREAD

**Issue by RohanPadmanabhan** [real-time-footfall-analysis/rtfa-web#30]
If organiser A sends a push notification to attendees then this notification is not displayed in organiser B's web interface until they refresh the page. As such if they do not refresh the page in a while they may be many notifications behind and may choose to send out similar messages to attendees

**Comment by ZeshanA** [comment]
Essentially the same issue as #29, not an enhancement we have time to add before the final presentation 😢
