### ISSUE TITLE
Poll current state db for live heat-map data every 5s

### ISSUE THREAD

**Issue by tompntn** [real-time-footfall-analysis/rtfa-web#45]
Need to ensure that the polling is the limiting factor in the end-to-end latency (movement event being sent to the api -> showing up on the heat-map).

**Comment by ZeshanA** [comment]
Can do – will get to this in ~20 minutes.

**Comment by tompntn** [comment]
It's not urgent at all - enjoy the holiday 😂

**Comment by ZeshanA** [comment]
Resolved in #46! Merry Christmas 🎄
