### ISSUE TITLE
App crashes when regions clicked on in heat map

### ISSUE THREAD

**Issue by RohanPadmanabhan** [real-time-footfall-analysis/rtfa-web#51]
When clicking on newly set up regions the app crashes and throws the following error.

![image](https://user-images.githubusercontent.com/26333869/50662911-d0def480-0f9f-11e9-9a9c-c6077105ba35.png)

Suspect that it is not receiving any data from the analytics API to display and unable to handle that case.

**Comment by ZeshanA** [comment]
Looking into this right now - will resolve tonight. Thanks for raising this issue!
